config/routes.rb
Rails.application.routes.draw do

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    get '/signup' => 'users#new'
    post '/users' => 'users#create'

    get '/auth/:provider/callback', to: 'sessions#create_with_instagram'
    get '/auth/failure', :to => 'sessions#failure'

    resources :users, only: [:index, :show, :update, :edit, :destroy] do
        resources :posts, only: [:index, :show, :new, :create, :update, :edit, :destroy]
        resources :braintree, only: [:new]
    end

      resources :users do
      member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
    
    post 'braintree/checkout'
    
    get "/allusers" => "users#all"

    root 'welcome#index'

end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController

def new
  @client_token = Braintree::ClientToken.generate
  # byebug
end


def checkout
	nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
	# byebug
	result = Braintree::Transaction.sale(
				:amount => "50.00", #this is currently hardcoded
				:payment_method_nonce => nonce_from_the_client,
				:options => {
											:submit_for_settlement => true
										})

if result.success?
	# @user
	# current_user.refreshtoken == nonce_from_the_client
	# byebug
	# current_user.update_attributes(:refreshtoken => nonce_from_the_client)
	 current_user.update_attributes(:payment => nonce_from_the_client )

 	redirect_to user_path(current_user), :flash => { :success => "Transaction successful!"}
else
redirect_to new_user_braintree_path(current_user), :flash => {:error => "Transaction filed , Please try again"}
 
  end
 end
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/views/braintree/new.html.erb
<h1>Payment Page</h1>

 
	<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>
  <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

  <div class="demo-frame">

   <%= form_for :checkout_form, url: braintree_checkout_path, html: {id: "cardForm"} do |form| %>

     <%= form.label :card_number, "Credit Number", html: {class: "hosted-fields--label"} %>
         <div id="card-number" class="hosted-field"></div>

     <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
     <div id="expiration-date" class="hosted-field"></div>

     <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"}%>
     <div id="cvv" class="hosted-field"></div>

     <%= form.hidden_field "payment_method_nonce" %>

     <div class="button-container">
   <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
     </div>
   <% end %>


 <script>

	  var form = document.querySelector('#cardForm');
                   var submit = document.querySelector("#submit-payment-btn");
                   // debugger
                   var authorization1 = '<%= @client_token %>'
                   braintree.client.create({
                   authorization: authorization1

                   }, function (clientErr, clientInstance) {
                     if (clientErr) {
                                            // Handle error in client creation
                       return;
                     }
 
                     braintree.hostedFields.create({
                       client: clientInstance,
                       styles: {
                         'input': {
                           'font-size': '14pt'
                         },
                         'input.invalid': {
                           'color': 'red'
                         },
                         'input.valid': {
                           'color': 'green'
                         }
                       },
                       fields: {
                         number: {
                           selector: '#card-number',
                           placeholder: '4111 1111 1111 1111'
                         },
                         cvv: {
                           selector: '#cvv',
                           placeholder: '123'
                         },
                         expirationDate: {
                           selector: '#expiration-date',
                           placeholder: '10/2019'
                         }
                       }
                     }, function (hostedFieldsErr, hostedFieldsInstance) {
                       if (hostedFieldsErr) {
                         // Handle error in Hosted Fields creation
                         return;
                       }
 
                       submit.removeAttribute('disabled');
 
                       form.addEventListener('submit', function (event) {
                         event.preventDefault();
 
                         hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
                           if (tokenizeErr) {
                             // Handle error in Hosted Fields tokenization
                             return;
                           }
 
                           // Put `payload.nonce` into the `payment-method-nonce` input, and then
                           // submit the form. Alternatively, you could send the nonce to your server
                           // with AJAX.
                           document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
 
                           form.submit();
                         });
                       }, false);
                     });
                   });
 
</script>
</div>