config/routes.rb
Rails.application.routes.draw do

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    get '/signup' => 'users#new'
    post '/users' => 'users#create'

    get '/auth/:provider/callback', to: 'sessions#create_with_instagram'
    get '/auth/failure', :to => 'sessions#failure'

    resources :users, only: [:index, :show, :update, :edit, :destroy] do
        resources :posts, only: [:index, :show, :new, :create, :update, :edit, :destroy]
        resources :braintree, only: [:new]
    end

      resources :users do
      member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
    
    post 'braintree/checkout'
    
    get "/allusers" => "users#all"

    root 'welcome#index'

end

app/models/user.rb
 class User < ActiveRecord::Base
    include Messenger
    include PgSearch
    # multisearchable :against => [:nick_name, :first_name]
    validates_confirmation_of :password

  # this for test model
  # ##################################
   # validates_presence_of :password
   # validates_presence_of :email
    validates :email, uniqueness: true
# ##################################
 # validates :email, format: {with: /\A([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})\z/,
 # message: "Your Email should Be like : example@exaple.com"}

     pg_search_scope :search,
                  against: [
                    :nick_name,
                    :first_name,
                    :email
                  ],
                  using: {
                    tsearch: {
                      prefix: true,
                      normalization: 2
                    }
                  }
    has_secure_password

    mount_uploader :avatar, AvatarUploader

    has_many :posts, dependent: :destroy
     
    has_many :active_relationships, class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy

    has_many :passive_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy

	 	has_many :following, through: :active_relationships, source: :followed
  	has_many :followers, through: :passive_relationships, source: :follower

    enum access_level: [:ordinary, :admin, :king_kong]

      # scope :nick_name, -> (nick_name) {where("nick_name like ?", "#{nick_name}")}
      # scope :first_name -> (first_name) {where("first_name like ?", "#{first_name}")}
 def clean_number
  @num = self.phone.scan(/\d+/).join
  # byebug
  # phone[0] == '1' ? phone[0] = '' : phone
  # phone unless phone.length != 16
end

  def self.perform_search(keyword)
    if keyword.present?
      then User.search(keyword)
       else 
      all
    end
  end

# def self.search(search)
#   if search
#     where(["nick_name LIKE ?","%#{search}%"])
#     where(["first_name LIKE ?","%#{search}%"])
#     where(["email LIKE ?","%#{search}%"])
#     else
#     all
#     end
#   end

def self.from_omniauth(auth_hash)
     # user = User.create!(first_name: auth_hash["extra"]["raw_info"]["first_name"], last_name: auth_hash["extra"]["raw_info"]["last_name"], email: auth_hash["extra"]["raw_info"]["email"])

    user = find_by(provider: auth_hash.provider, uid: auth_hash.uid)
    user = create(uid: auth_hash.uid, provider: auth_hash.provider,:first_name => auth_hash['info']['firstname'], :nick_name => auth_hash['info']['nickname'], :password => auth_hash['uid'], :avatar => auth_hash["image"]) if user.nil?
        # user = create(:first_name => auth_hash['info']['firstname'], :nick_name => auth_hash['info']['name'], :password => auth_hash['uid'] )
    user.accesstoken = auth_hash.credentials.token
    # user.password = '   '
    user.refreshtoken = auth_hash.credentials.refresh_token
    # user.email = auth_hash.email
    # user.nick_name = auth_hash.info.username
    # user.email = auth_hash['info']['email']
    # user.nick_name = auth_hash['info']['username']
  user.save!
    user
    # where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_initialize.tap do |user|
    # user.provider = auth_hash.provider
    # user.uid = auth_hash.uid
    # user.first_name = auth_hash.info.first_name
    # user.acesstoken = auth_hash.credentials.token
    #  user.save
    #  user
  #-----------
    # user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
    # user.nick_name = auth_hash['info']['username']
    # byebug
    # user.avatar = auth_hash['info']['image']
    # # user.urls = auth_hash['info']['urls']['instagram']
    # user.password = ' '
    # user.save!
    # user
   
  end

      
  def instagram
    user.where( :provider => "instagram" ).first
  end

  def instagram_client
    @instagram_client ||= Instagram.client( access_token: instagram.accesstoken )
  end    

 

 	def follow(other_user)
   following << other_user
    # relationships.create(followed_id: other_user.id)
  end

      # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)

     # relationships.find_by(followed_id: other_user.id).destroy
  end

     # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
      # relationships.find_by(followed_id: other_user.id) 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	

	def index

	end

	def show
		@user = User.find_by_id(params[:id])
 	end

def new
end

def create
	user = User.new(new_user)
	if user.save
		session[:user_id] = user.id
		redirect_to '/'
		flash[:notice] = "Successfully created a new user"

 else
		redirect_to signup_path
		flash[:notice] = "Email must be like example@ex.com && Password must be at lest 6 chracters" 
 
	end
end

def edit
	@user = User.find(params[:id])
end

def update
	@user = User.find(params[:id])
		@user.update(new_user)

			if @user.save
						@user.send_sms(@user.phone) unless @user.phone == ""
						# @user.send_sms(@user.phone) unless @user = params[:user][:phone] != nil

 
				redirect_to user_path(current_user)
					flash[:notice] = "Successfully updated"
			else
					redirect_to edit_user_path(current_user)
				flash[:notice] = "Error"
		end
end

def destroy
		@user = User.find(current_user)
		@user.destroy
		redirect_to logout_path
# 		flash[:notice] = "Successfully Deleted"
end

def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
end

def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
end
def all
		 # @user = User.search(params[:search]).all
  	 	 # @user = User.all
		 # @user = PgSearch.multisearch(params[:search])
	if params[:search].present?
      @user = User.perform_search(params[:search])
    		else
      @user = User.all
	end
end

def send_text
		@num = User.new(new_user)
		# byebug
		# @after_scan = @num.clean_number
		# @num.clean_number
		# byebug
		@num.send_sms(@num.phone)#()
		redirect_to root_path
		      flash[:danger] = ".Done"

	end

	private
	 
	def new_user
	params.require(:user).permit(:nick_name, :first_name, :last_name, :phone, :email, :password, :avatar, :access_level)

	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user %>
	 <div id="follow_form">
  		<% if current_user.following? %>
    			<%= render 'unfollow' %>
  				<% else %>
    	<%= render 'follow' %>
  	<% end %>
  </div>
<% end %>

app/views/users/_stats.html.erb
 <% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
        <%= @user.following.count %>	 
          </strong>
    	     following 
  	         </a>
	         <a href="<%= followers_user_path(@user) %>">
          <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/all.html.erb
<h3> All User </h3>

 <div class="artist_search.form-group">
  <%= form_tag(allusers_path, method: "get") do %>
    <%= text_field_tag :search, nil, placeholder: "Search User in first Name, Nick Name, Email ...", class: "form-control" %>
   	<%= submit_tag "search"%>
   <% end %>
</div>

<% @user.each do |user|%>

	<%= user.first_name %></br>
	 		<p><%= image_tag user.avatar.url(:thumb) %></p></br>
 	<span><%= link_to "view my profile", user %></span></br>

<% end %>

app/views/users/edit.html.erb
<h2>Edit Page</h2>

<% if @user == current_user or current_user.king_kong? or current_user.admin? %>

 <%= form_for @user do |f| %>
 
  Nick Name    : <%= f.text_field :nick_name %></br>
     First Name   : <%= f.text_field :first_name %></br>
        Last Name    : <%= f.text_field :last_name %></br>
      Phone Number : <%= f.text_field :phone %> </br>
  Email        : <%= f.text_field :email %></br>

  <% if current_user.king_kong? or current_user.email == 'nabil@gmail.com'%>
  
  <div class="field">
    <%= f.label :access_level, "Who are you? " %><br/>
        <%= f.select :access_level, ['ordinary','admin','king_kong'] %>
          <% elsif current_user.admin? %>
            <%= f.label "you are admin " %><br/>
          <%else %>
      <%= f.label "you are user " %><br/>
    <% end %>
  </div>

  <div class="form-group">
		<%= f.label :avatar, 'User Photo', class:'col-sm-2 control-label' %>
  		<div class="col-sm-10">
    	<%= f.file_field :avatar  %>
  	</div>
	</div>
	
    <%= f.submit "Update" %>

<% end %>
  <% if @user == current_user or current_user.king_kong?  %>
    <%= link_to "Delete Account", @user, method: :delete, data: {confirm: "You will DELETE",:style=>'color:red;', :class => "css_class"} %>
      <% else %>
    <p>you cant delete the is user coz you Admin </p>
  <% end %>
<% end %>
 

app/views/users/new.html.erb
<h2>Sign Up</h2>


<%= form_for :user, url: '/users' do |f| %>

  Nick Name: <%= f.text_field :nick_name %></br>

  		Email: <%= f.text_field :email %></br>

  		Password: <%= f.password_field :password %></br>

 		Password confirmation: <%= f.password_field :password_confirmation %></br>
   <%= f.submit "Submit" %>
   
<% end %>

app/views/users/show.html.erb
<h2>Profile</h2>
  <%if current_user.payment == nil %>
      <%= link_to "Premier Account 50$ ", new_user_braintree_path(current_user) %>
        <% else %>
      <%= link_to "Congratulation you are premier" %>
    <%end%>

    <% if current_user != nil%>
        <% if current_user.king_kong? %>
         <h3>Welcome <%= current_user.first_name %> your access level is King Kong</h3>
          <% elsif current_user.admin? %>
          <h3>Welcome,<%= current_user.first_name %> your access level is Admin</h3>
        <% else %>
      <h3>Welcome</h3>
    <% end %>

 
    <p><%= image_tag @user.avatar.url(:thumb) %></p>
	     <p> Nick Name : <%= @user.nick_name%></p>
    <p> Email: <%= @user.email%> </p>

      <section class="stats">
         <%= render 'stats' %>
      </section>
	<!-- ============== -->

<% provide(:title, @user.first_name) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
         <%= @user.first_name %>
         <% if @user.posts.any? %>
          <p>posts (<%= @user.posts.count %>)</p>
         </h1>
       </section>
      </aside>
     <% end %>
  </div>
 
 <!--if for access level for king_kong  -->
<% if current_user.king_kong? or current_user.admin?%>
  <%= link_to "Edit User", edit_user_path(@user)%></br>
<%end%>


 <% if current_user.id == @user.id %>
    <%= link_to "Edit User", edit_user_path(current_user)%></br>
  <% else %>

<!-- follow unfollow button  -->

  <div id="follow_form">
    <% if current_user.following?(@user) %>
       <%= render 'unfollow' %>
         <% else %>
            <%= render 'follow' %>
          <% end %>
        </div>
      </br>
    <%= link_to "Sign in", login_path%>
  <% end %>
 

  <%else%>
  <p>sign in</p>
  <%end%>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
    		 <h1><%= @user.first_name %></h1>
     		 		<span><%= link_to "view my profile", @user %></span>
   				 <span><b>posts:</b> <%= @user.posts.count %></span>
          <div class="user_avatars">
        <p><%= image_tag @user.avatar.url(:thumb) %></p>
  	  </div>
    </section>

    <section class="stats">
    	  <%= render 'stats' %>
    		  <% if @users.any? %>
    	 		 <% end %>
   		 </section>
  	</aside>

  <div class="col-md-8">

    <h1><%= @title %></h1>
    <% if @users.any? %>
      <ul class="users follow">
      	<%= @users.each do |n|%>
         <p><%= image_tag n.avatar.url(:thumb) %></p>
	     	   <span><%= link_to "view my profile", n %></span>

      	   <p>First Name: <%= n.first_name %></p>
      	 <p>Posts: <%= n.posts.count %></p>
	       <% end %>
  	   </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>