config/routes.rb
Rails.application.routes.draw do

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    get '/signup' => 'users#new'
    post '/users' => 'users#create'

    get '/auth/:provider/callback', to: 'sessions#create_with_instagram'
    get '/auth/failure', :to => 'sessions#failure'

    resources :users, only: [:index, :show, :update, :edit, :destroy] do
        resources :posts, only: [:index, :show, :new, :create, :update, :edit, :destroy]
        resources :braintree, only: [:new]
    end

      resources :users do
      member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
    
    post 'braintree/checkout'
    
    get "/allusers" => "users#all"

    root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageGallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>

<nav class="navbar navbar-inverse">

	<div class="container-fluid">
     <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
       	 	<span class="sr-only">Toggle navigation</span>
        	<span class="icon-bar"></span>
       	 <span class="icon-bar"></span>
       	 <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="/">Image Gallery</a>

 
      <% if current_user %>
			<%= link_to "My Profile", user_path(current_user.id), class:"navbar-brand" %>
			<%= link_to "New Post", new_user_post_path(current_user), class:"navbar-brand"%>
      <%= link_to "My Posts", user_posts_path(current_user), class:"navbar-brand"%>

      <%= link_to "All User", allusers_path, class:"navbar-brand" %>
      <% end %>

      <div class="navbar-brand">
      	  <% if current_user %>
  					Signed in as <%= current_user.email %> | <%= link_to "Logout", '/logout' %>
						<% else %>
  					<%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %> |    <%= link_to 'Sign in with Instagram', '/auth/instagram'%>

					<% end %>
  		</div>

    </div>
 	 </div>
			</nav>

<%= yield %>
<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
 </div>
</body>
</html>